# quotes.py

import random

QUOTES = [
"Silence is not empty; it is full of peace.",
"Everything unfolds without effort.",
"The doer is imagined; life simply happens.",
"Peace is your natural state.",
"Let go, and see what remains.",
"Witness, do not interfere.",
"What is, is enough.",
"The mind creates noise; awareness is quiet.",
"You are not the storm, you are the sky.",
"Nothing is missing in this moment.",
"Life flows by itself.",
"In stillness, truth reveals itself.",
"The heart knows without thinking.",
"Awareness needs no improvement.",
"Stop chasing; start seeing.",
"The present moment is complete.",
"Let things be as they are.",
"Silence answers what words cannot.",
"You are the watcher, not the waves.",
"Calmness is your original nature.",
"Nothing to fix, nothing to change.",
"Love arises naturally in clarity.",
"The witness is untouched.",
"Rest as you are.",
"Peace is closer than breath.",
"Thoughts come and go; you remain.",
"Life moves without a controller.",
"In acceptance, there is freedom.",
"Just observe.",
"Stillness is strength.",
"The ego struggles; awareness relaxes.",
"Being is effortless.",
"The truth is simple.",
"Let understanding replace effort.",
"Nothing belongs to you, yet all appears in you.",
"Silence is the highest teaching.",
"Relax into the present.",
"The mind seeks; the heart rests.",
"Freedom is already here.",
"Drop the story.",
"Awareness is untouched by events.",
"Stop resisting.",
"Let clarity shine.",
"You are the space of experience.",
"Do nothing, see everything.",
"Life is happening.",
"Peace does not need a reason.",
"Stay as the witness.",
"Let thoughts dissolve naturally.",
"Truth is immediate.",
"There is no doer behind action.",
"Compassion flows from understanding.",
"The present is sacred.",
"Let go of control.",
"Stillness speaks.",
"Nothing is personal.",
"Awareness is vast.",
"Love needs no effort.",
"Just be.",
"The mind complicates; truth simplifies.",
"Freedom is in seeing clearly.",
"Silence heals.",
"You are not your thoughts.",
"Everything changes; you remain.",
"Clarity ends confusion.",
"Rest deeply.",
"Peace is within.",
"The observer is free.",
"Life is a play of appearances.",
"Nothing to achieve.",
"The heart is already full.",
"Witness without judgment.",
"The sky is never disturbed by clouds.",
"Let the moment unfold.",
"Being is enough.",
"No need to hurry.",
"The self is pure awareness.",
"Everything arises and fades.",
"Calmness is natural.",
"Drop the burden of control.",
"See, and be free.",
"Peace is effortless.",
"Life knows what it is doing.",
"Awareness is untouched.",
"Relax the mind.",
"The now is complete.",
"Nothing lasts, nothing binds.",
"Freedom is your essence.",
"Let silence guide.",
"You are not separate.",
"The watcher is still.",
"Everything is passing.",
"Love is your nature.",
"Rest in simplicity.",
"See without interference.",
"Nothing is outside awareness.",
"The present holds everything.",
"Being is bliss.",
"Just remain aware."
]

def get_random_quote():
    return random.choice(QUOTES)